namespace: extreme
name: nos
version: 0.1.0
readme: README.md
authors:
    - Ujwal Komarla
description: An Ansible collection for managing Extreme Networks devices running NOS.
license: GPL-3.0-or-later
license_file: COPYING
dependencies:
  "ansible.netcommon": "*"
repository: git@github.com:extremenetworks/ansible_collections.extreme.nos.git
documentation: https://github.com/extremenetworks/ansible_collections.extreme.nos/tree/master/docs
homepage: https://github.com/extremenetworks/ansible_collections.extreme.nos
issues: https://github.com/extremenetworks/ansible_collections.extreme.nos/issues
tags:
    - networking
    - nos
    - extreme
    - switching
    - collection
